on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Merge commit
        run: |
          git fetch --unshallow
          git checkout v2-develop
          git pull
          git merge main --no-ff --no-edit -m 'chore: automatic sync v2 into v2-develop'
          git push
      - name: Create PR to develop
        if: ${{ failure() }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create -B v2-develop --title 'Automatic Sync Pull Request' --body 'This PR is generated automatically with changes pushed into `v2` branch. `v2` and `v2-develop` branches should be in-sync.' --label automerge || true
