on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Merge commit
        run: "git merge v2-develop --no-ff -m 'chore: automatic sync v2 into v2-develop'"
      # - name: Create PR to develop
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh pr create -B v2-develop --title 'Automatic Sync Pull Request' --body 'This PR is generated automatically with changes pushed into `v2` branch. `v2` and `v2-develop` branches should be in-sync.' --label automerge || true
      # # - name: Merge created PR
      # #   env:
      # #     GH_TOKEN: ${{ github.token }}
      # #   run: gh pr merge --auto --merge
