on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          # message: Auto-commit with changes after publish
          new_branch: v2-develop
