on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Create Pull Request
        uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "My pull request title"
          body: "My pull request body"
          branch: "v2-develop"
          commit-message: "My commit message for uncommitted changes in lib/ folder"
          author: "Lorem J. Ipsum <lorem@example.com>"
          # auto-merge: squash
