on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: Auto PR with changes after publish
          body: Pull request created automatically when any change land into `v2` so branches would be in sync.
          branch: v2-develop
