on:
  pull_request:
    types:
      - opened
      - labeled
      - reopened
      - synchronize
      - ready_for_review
      - edited

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.head_ref, 'main' )}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
