name: Create changelog
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  create-changelog:
    name: Create changelog
    runs-on: ubuntu-latest
    if: ${{ startsWith( github.head_ref, 'v2-release' ) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn --immutable
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: "!exit-rc"
      - name: Enter pre-release changelog if !exit-rc comment does not exists
        if: ${{ !steps.fc.outputs.comment-id }}
        run: echo pre enter rc
      - name: Create PR with changelog
        run: echo Changelog
