name: Test
on:
  push:
    branches:
      - main

jobs:
  commit-message:
    name: Check commit message
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message
        run: echo "Last commit message is ${{ github.event.head_commit.message }}"
