name: Create changelog
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - 'v2-release/**'

jobs:
  create-changelog:
    name: Create changelog
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: "!exit-rc"
          direction: "last"
      # - run: |
      #     echo ${{ steps.fc.outputs.comment-id }}
      #     echo ${{ steps.fc.outputs.comment-body }}
      #     echo ${{ steps.fc.outputs.comment-author }}
      #     echo ${{ steps.fc.outputs.comment-created-at }}
      - name: Enter pre-release changelog if !exit-rc comment does not exists
        if: ${{ steps.fc.outputs.comment-id }}
        run: echo pre enter rc
      - name: Generate changesets changelog
        run: echo changelog!
