on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - run: gh pr comment ${{ github.event.pull_request.number }} -b "Hello there"
        env:
          GH_TOKEN: ${{ github.token }}
