on: push

jobs:
  console-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Console Branch name
        run: echo ${{ github.ref }}

  console-log:
    runs-on: ubuntu-latest
    needs: [console-echo]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
      - name: Run node file
        env:
          branchName: ${{ github.ref }}
        run: node supercool
